# Generated by Django 5.2.7 on 2025-11-25 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recordatorio', 'Recordatorio'), ('evento', 'Evento'), ('sistema', 'Sistema')], max_length=50)),
                ('etiqueta', models.CharField(blank=True, choices=[('recordatorio_15m', 'Recordatorio 15 Minutos'), ('recordatorio_1h', 'Recordatorio 1 Hora'), ('recordatorio_1d', 'Recordatorio 1 Día'), ('general', 'General')], max_length=50, null=True)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_generadas', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leida', models.BooleanField(default=False)),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='notificaciones.notificacion')),
            ],
            options={
                'verbose_name': 'Usuario - Notificación',
                'verbose_name_plural': 'Usuarios - Notificaciones',
            },
        ),
    ]
