# Generated by Django 5.2.7 on 2025-11-22 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_limpiar_categorias_antiguas'),
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='etiqueta',
            field=models.CharField(blank=True, choices=[('recordatorio_15m', 'Recordatorio 15 Minutos'), ('recordatorio_2h', 'Recordatorio 2 Horas'), ('general', 'General')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_generadas', to='eventos.evento'),
        ),
    ]
