# Generated by Django 5.2.7 on 2025-11-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_notificacion_etiqueta_notificacion_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='leida',
        ),
        migrations.AddField(
            model_name='usuarionotificacion',
            name='leida',
            field=models.BooleanField(default=False),
        ),
    ]
