# Generated by Django 5.2.7 on 2025-11-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_remove_notificacion_leida_usuarionotificacion_leida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='etiqueta',
            field=models.CharField(blank=True, choices=[('recordatorio_15m', 'Recordatorio 15 Minutos'), ('recordatorio_1h', 'Recordatorio 1 Hora'), ('recordatorio_2h', 'Recordatorio 2 Horas'), ('general', 'General')], max_length=50, null=True),
        ),
    ]
