# Generated by Django 5.2.7 on 2025-11-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0004_alter_notificacion_etiqueta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='etiqueta',
            field=models.CharField(blank=True, choices=[('recordatorio_15m', 'Recordatorio 15 Minutos'), ('recordatorio_1h', 'Recordatorio 1 Hora'), ('recordatorio_1d', 'Recordatorio 1 Día'), ('general', 'General')], max_length=50, null=True),
        ),
    ]
