# Generated by Django - NO BORRAR ESTA LÍNEA

from django.db import migrations


def crear_roles_iniciales(apps, schema_editor):
    """
    Crea los roles iniciales del sistema.
    Esta función se ejecuta cuando se aplica la migración.
    """
    # Obtener el modelo Rol (de forma segura para migraciones)
    Rol = apps.get_model('usuarios', 'Rol')
    
    # Lista de roles a crear
    roles_iniciales = [
        'Estudiante',
        'Profesor', 
        'Admin'
    ]
    
    # Crear cada rol si no existe
    for nombre_rol in roles_iniciales:
        Rol.objects.get_or_create(nombre=nombre_rol)
        print(f'✅ Rol "{nombre_rol}" verificado/creado')


def eliminar_roles_iniciales(apps, schema_editor):
    """
    Rollback: Elimina los roles si necesitas revertir la migración.
    """
    Rol = apps.get_model('usuarios', 'Rol')
    
    roles_a_eliminar = ['Estudiante', 'Profesor', 'Admin']
    
    Rol.objects.filter(nombre__in=roles_a_eliminar).delete()
    print('🗑️  Roles iniciales eliminados')


class Migration(migrations.Migration):
    
    # Esta migración depende de la migración anterior
    dependencies = [
        ('usuarios', '0001_initial'),
    ]
    
    # Operaciones a ejecutar
    operations = [
    migrations.RunPython(
        crear_roles_iniciales,      # ← Con indentación correcta
        eliminar_roles_iniciales    # ← Con indentación correcta
    ),
    ]