# Generated by Django 5.2.7 on 2025-11-06 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_seed_initial_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='usuarios.rol'),
        ),
    ]
