# Generated by Django 5.0.6 on 2025-11-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0004_modificar_usuario"),
    ]

    operations = [
        # is_active e is_staff ya existen (vienen de AbstractUser), no necesitan agregarse
        # Solo modificamos codigo_estudiantil para quitarle unique
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Quitar unique constraint de codigo_estudiantil si existe
                migrations.RunSQL(
                    sql="""
                        DO $$ 
                        BEGIN 
                            IF EXISTS (
                                SELECT 1 FROM information_schema.table_constraints 
                                WHERE table_name='usuarios_usuario' 
                                AND constraint_name LIKE '%codigo_estudiantil%unique%'
                            ) THEN
                                ALTER TABLE usuarios_usuario 
                                DROP CONSTRAINT IF EXISTS usuarios_usuario_codigo_estudiantil_key;
                            END IF;
                        END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                # Modificar el campo en el estado de Django (quitar unique)
                migrations.AlterField(
                    model_name="usuario",
                    name="codigo_estudiantil",
                    field=models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
        ),
    ]
