# Generated by Django 5.2.7 on 2025-11-07 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0004_modificar_usuario"),
        ("usuarios", "0005_usuario_is_active_usuario_is_staff_and_more"),
    ]

    operations = []
