# Generated by Django 5.2.7 on 2025-11-07 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0006_merge_20251107_0529"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE usuarios_usuario DROP COLUMN IF EXISTS estado_cuenta",
            reverse_sql="ALTER TABLE usuarios_usuario ADD COLUMN estado_cuenta VARCHAR(20) DEFAULT 'pendiente'",
        ),
    ]
