# Generated by Django 5.2.7 on 2025-11-20 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_restore_staff_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='estado_cuenta',
        ),
    ]
