<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-11-20 23:07
=======
# Generated by Django 5.2.7 on 2025-11-20 22:22
>>>>>>> 7a5532a136307fccf049b016240b7c73a771ffe7

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_restore_staff_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='estado_cuenta',
        ),
    ]
