# Generated by Django 5.2.7 on 2025-11-01 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_evento_titulo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='asistentes',
            field=models.ManyToManyField(related_name='eventos_asistidos', through='eventos.Inscripcion', to=settings.AUTH_USER_MODEL),
        ),
    ]
