# Generated by Django 5.2.7 on 2025-11-06 15:10

from django.db import migrations


def crear_categorias(apps, schema_editor):
    CategoriaEvento = apps.get_model('eventos', 'CategoriaEvento')
    categorias = ["Académico", "Deportivo", "Cultural", "Social"]

    for nombre in categorias:
        CategoriaEvento.objects.get_or_create(nombre=nombre)

class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(crear_categorias),
    ]
