# Generated by Django 5.2.7 on 2025-11-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_alter_evento_categoria'),
        ('eventos', '0005_seed_categorias'),
    ]

    operations = [
    ]
