# Generated by Django 5.0.6 on 2025-11-06 22:34

from django.db import migrations

def crear_categorias(apps, schema_editor):
    CategoriaEvento = apps.get_model('eventos', 'CategoriaEvento')
    categorias = [
        "Música",
        "Deporte", 
        "Educación",
        "Cultural",
        "Aficiones",
        "Vacaciones",
        "Gastronomía",
        "Artes Escénicas",
        "Citas"
    ]
    for nombre in categorias:
        CategoriaEvento.objects.get_or_create(nombre=nombre)
    
class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0006_merge_20251106_1513"),
    ]
    operations = [
        migrations.RunPython(crear_categorias),
    ]
