# Generated by Django 5.2.7 on 2025-11-23 18:39

from django.db import migrations, models
import secrets
import string


def generar_codigo_confirmacion():
    """Genera un código aleatorio de 6 caracteres alfanuméricos"""
    caracteres = string.ascii_uppercase + string.digits
    return ''.join(secrets.choice(caracteres) for _ in range(6))


def generar_codigos_para_eventos_existentes(apps, schema_editor):
    """Genera códigos de confirmación para eventos existentes"""
    Evento = apps.get_model('eventos', 'Evento')
    codigos_usados = set()
    
    for evento in Evento.objects.all():
        # Generar código único
        codigo = generar_codigo_confirmacion()
        while codigo in codigos_usados or Evento.objects.filter(codigo_confirmacion=codigo).exists():
            codigo = generar_codigo_confirmacion()
        codigos_usados.add(codigo)
        evento.codigo_confirmacion = codigo
        evento.save(update_fields=['codigo_confirmacion'])


def reverse_generar_codigos(apps, schema_editor):
    """Función reversa - no hace nada"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_limpiar_categorias_antiguas'),
    ]

    operations = [
        # Primero agregar el campo como nullable
        migrations.AddField(
            model_name='evento',
            name='codigo_confirmacion',
            field=models.CharField(max_length=10, null=True, blank=True, editable=False, unique=False),
        ),
        # Generar códigos para eventos existentes
        migrations.RunPython(
            generar_codigos_para_eventos_existentes,
            reverse_generar_codigos,
        ),
        # Ahora hacer el campo NOT NULL y único
        migrations.AlterField(
            model_name='evento',
            name='codigo_confirmacion',
            field=models.CharField(max_length=10, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='asistencia_confirmada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='fecha_confirmacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
