"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import environ
from datetime import timedelta
import dj_database_url
from celery.schedules import crontab, schedule

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
PROJECT_ROOT = BASE_DIR.parent
environ.Env.read_env(os.path.join(PROJECT_ROOT, '.env'))

SECRET_KEY = os.environ.get('SECRET_KEY') or env('SECRET_KEY', default='django-insecure-temporary-key-change-in-production')
DEBUG = env.bool('DEBUG', default=False) #convierte la cadena "True" o "False" del .env en un valor booleano real.

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])

# Configuración de Redis con valores por defecto
# En Docker, usar 'redis:6379', en desarrollo local usar 'localhost:6379'
REDIS_PASS = env('REDIS_PASS', default='')
REDIS_ENDPOINT = env('REDIS_ENDPOINT', default='redis:6379' if os.environ.get('DOCKER_CONTAINER') else 'localhost:6379')

# Construir URL de Redis: solo incluir contraseña si está configurada y no está vacía
# Verificar explícitamente que REDIS_PASS no sea None, vacío o solo espacios
# También verificar que no sea la cadena literal 'None' o 'null'
# Si REDIS_PASS está vacío o no está definido, usar URL sin autenticación
# IMPORTANTE: Cuando REDIS_PASS viene de Docker Compose como cadena vacía,
# puede estar presente como variable de entorno pero con valor vacío
# Verificar explícitamente que tenga un valor real antes de usarlo
redis_pass_raw = os.environ.get('REDIS_PASS', None)
# Verificar que existe, no es None, no está vacío y no es solo espacios
if redis_pass_raw is not None and str(redis_pass_raw).strip():
    redis_pass_clean = str(redis_pass_raw).strip()
    # Verificar que no sea un valor inválido
    if redis_pass_clean.lower() not in ('none', 'null', ''):
        REDIS_URL = f"redis://:{redis_pass_clean}@{REDIS_ENDPOINT}"
    else:
        REDIS_URL = f"redis://{REDIS_ENDPOINT}"
else:
    # Si REDIS_PASS no está definido o está vacío, usar URL sin autenticación
    REDIS_URL = f"redis://{REDIS_ENDPOINT}"

# Application definition

INSTALLED_APPS = [
    'daphne', # Para soporte ASGI, debe ir primero
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'channels',              
    'django_celery_beat',
    # Apps locales
    'apps.usuarios',
    'apps.eventos',
    'apps.notificaciones',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'
ASGI_APPLICATION = 'backend.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=env('DATABASE_URL'),
        conn_max_age=600,
        conn_health_checks=True,  
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-co'  # Cambiar a español de Colombia

TIME_ZONE = 'America/Bogota'  # Cambiar de 'UTC' a 'America/Bogota'

USE_I18N = True

USE_TZ = True  # Asegúrate de que esto esté en True


# Archivos estáticos y multimedia
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración del modelo de usuario personalizado
AUTH_USER_MODEL = 'usuarios.Usuario'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'apps.usuarios.auth.CookieJWTAuthentication',
    ],
    # DEFAULT_PERMISSION_CLASSES: Permiso por defecto para todos los viewsets
    # Si un viewset no define permission_classes, usará este.
    # IsAuthenticated requiere autenticación por defecto (más seguro).
    # Cada viewset puede sobrescribir esto con su propio get_permissions() o permission_classes
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_RENDERER_CLASSES': [
    'rest_framework.renderers.JSONRenderer',          # La API responde en JSON (el formato estándar)
    'rest_framework.renderers.BrowsableAPIRenderer',  # Habilita la interfaz web interactiva de DRF
    ],

    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
    'DEFAULT_THROTTLE_CLASSES': [
    'rest_framework.throttling.UserRateThrottle',
    'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
    'user': '100000/day',
    'anon': '10000/day',
    },
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.NamespaceVersioning',
    'DATETIME_FORMAT': "%Y-%m-%d %H:%M:%S",
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_OBTAIN_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenObtainPairSerializer',
}

# Configuración CORS - Seguridad mejorada
# En producción, usar CORS_ALLOWED_ORIGINS con orígenes específicos
CORS_ALLOW_ALL_ORIGINS = env.bool('CORS_ALLOW_ALL_ORIGINS', default=DEBUG)  # Solo True en desarrollo
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[
    'http://localhost:8080',
    'http://127.0.0.1:8080',
])

# Importante añadir en el frontend credentials: 'include' para que funcione
CORS_ALLOW_CREDENTIALS = True

# Configuración adicional para asegurar que las cookies funcionen
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Permitir que las cookies se envíen en las solicitudes
CORS_EXPOSE_HEADERS = ['Set-Cookie']

# --- CONFIGURACIÓN DE REAL-TIME & TAREAS ---

# 1. Configuración de Celery
CELERY_BROKER_URL = REDIS_URL # Lee la URL que pusimos en el .env
CELERY_RESULT_BACKEND = REDIS_URL # Almacenar resultados de las tareas en Redis
CELERY_ACCEPT_CONTENT = ['json'] # Aceptar contenido en formato JSON
CELERY_TASK_SERIALIZER = 'json' # Serializar tareas en formato JSON
CELERY_TIMEZONE = 'America/Bogota' # O tu zona horaria


EMAIL_BACKEND = env('EMAIL_BACKEND',default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST= env('EMAIL_HOST',default='smtp.gmail.com')
EMAIL_PORT=env.int('EMAIL_PORT',default=587)
EMAIL_USE_TLS=env.bool('EMAIL_USE_TLS',default=True)
EMAIL_HOST_USER=env('EMAIL_HOST_USER',default='eventifyuv@gmail.com')
EMAIL_HOST_PASSWORD=env('EMAIL_HOST_PASSWORD',default='')
DEFAULT_FROM_EMAIL=env('DEFAULT_FROM_EMAIL',default=EMAIL_HOST_USER)



CELERY_BEAT_SCHEDULE = {
    'notificar-eventos-proximos': {
        'task': 'apps.notificaciones.tasks.notificar_eventos_proximos',
        'schedule': schedule(run_every=timedelta(seconds=15)),  # Cada 15 segundos
    },
    'limpiar-notificaciones-eventos-finalizados': {
        'task': 'apps.notificaciones.tasks.limpiar_notificaciones_eventos_finalizados',
        'schedule': schedule(run_every=timedelta(hours=12)),  # Cada 12 horas (medio día)
    },
}

CHANNEL_LAYERS = {

    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
        }
    
    }
}